articles/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import ArticleCreateView, ArticleListView, ArticleUpdateView, ArticleDetailView, ArticleDeleteView

app_name = 'articles'
urlpatterns = [
    path('', ArticleListView.as_view(), name='blog'),
    path('create/', login_required(ArticleCreateView.as_view()), name='create'),
    path('<slug:slug>', ArticleDetailView.as_view(), name='detail'),
    path('<slug:slug>/update/', login_required(ArticleUpdateView.as_view()), name='update'),
    path('<slug:slug>/delete/', login_required(ArticleDeleteView.as_view()), name='delete'),
]

guardian_insurance_agency/urls.py
from django.contrib import admin
from django.urls import path, include

from pages.views import (
    HomeView,
    PersonalView,
    CommercialView,
    ContactView,
    AboutView
)

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('personal/', PersonalView.as_view(), name='personal'),
    path('commercial/', CommercialView.as_view(), name='commercial'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('about/', AboutView.as_view(), name='about'),
    path('blog/', include('articles.urls')),
    path('staff/', include('staff.urls')),
    path('admin/', admin.site.urls),
]

staff/urls.py
from django.urls import path

from .views import staff_home_view, login_view, logout_view

app_name = 'staff'
urlpatterns = [
    path('', staff_home_view, name='staff'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

templates/pages/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="about-us py-5 " id="about-us">
    <div class="container mt-5">
	<div class="row">
		<div class="col-md-6">
		    <h1 class=''>Welcome!</h1>
		    <h2>Learn More About Us</h2>
		    <hr>
		    <p class="lead"> Guardian Insurance Agency has been in business for 23 years. We offer the best customer service and have many companies available to us. That means you not only get the best prices, but you also get the best and most comprehensive coverage for whatever you need to insure.</p>
		    <p class="lead">We’re always available to help with any situation. Is there an emergency? You can even reach us in the evening or on the weekend. We don’t only pride ourselves on having the best service we also ensure that you have the best and most comprehensive policies for whatever your needs are. We won’t cut important parts of a policy just to lower your price. We’ll make sure you have the best policy with the best price.</p>
		</div>
		<div class="col-md-6 d-flex align-items-center">
		    <img class="img-fluid" src="{% static 'images/logo-alt.png'%}"alt="">
		</div>
	</div>
</div>
</section>
{% endblock %}

templates/pages/commercial.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% include 'pages/partials/small-header.html'%}
{% include 'pages/partials/small-cards-and-features.html' %}

{% endblock %}

templates/pages/contact.html
{% extends 'base.html' %}
{% block content %}

<section id="contact-form" class="mb-4 container">
    <h2 class="h1-responsive font-weight-bold text-center my-4">Contact us</h2>
    <p class="text-center w-responsive mx-auto mb-5">Do you have any questions? Please do not hesitate to contact us directly. Our team will come back to you within
        a matter of hours to help you.</p>

     {% if messages %}
     {% for message in messages %}
         <div class="text-center alert alert-{{ message.tags }}">
             <h5>{{ message|safe }}</h5>
         </div>
     {% endfor %}
    {% endif %}

    <div class="row">
        <!-- Contact form section -->
        {{ form.non_field_errors }}
        <div class="col-md-8 mb-md-0 mb-5">
            <form id="contact-form" name="contact-form" method="POST"> {% csrf_token %}

                <div class="row">                    
                    <div class="col-md-12">
                        <div class="md-form mb-0">
                            {{ form.name.errors }}
                            {{ form.name }}
                            <label for="{{ form.name.id_for_label }}" class="">Your name or company</label>
                        </div>
                    </div>
                </div>

                <div class="row">                    
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            {{ form.phone_number.errors }}
                            {{ form.phone_number }}
                            <label for="{{ form.phone_nubmer.id_for_label }}" class="">Your phone number</label>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            {{ form.email.errors }}
                            {{ form.email }}
                            <label for={{ form.email.id_for_label }} class="">Your email</label>
                        </div>
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0">
                            {{ form.subject.errors }}
                            {{ form.subject }}
                            <label for="{{ form.subject.id_for_label }}" class="">Subject</label>
                        </div>
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form">
                            {{ form.message.errors }}
                            {{ form.message }}
                            <label for="{{ form.message.id_for_label }}">Your message</label>
                        </div>
                    </div>
                </div>
            <div class="text-center text-md-left">
                <input class="btn btn-primary" type="submit" value="Send">
            </div>
            <div class="status"></div>
            </form>

         
        </div>
        
        <!--Information Section-->
        <div class="col-md-4 text-center">
            <ul class="list-unstyled mb-0">
                <li><i class="fas fa-map-marker-alt fa-2x"></i>
                    <p>33 W Higgins Rd, Suite 2100 <br>
                    South Barrington, IL 60010</p>
                </li>

                <li>
                <i class="fas fa-phone mt-4 fa-2x"></i>
                    <p>(847) 485-1550</p>
                <i class="fas fa-fax mt-4 fa-2x"></i>
                    <p>(847) 489-6700</p>
                </li>

                <li><i class="fas fa-envelope mt-4 fa-2x"></i>
                    <p>personal: service@emrz-ins.com <br> commercial: erzinsurance@gmail.com</p>
                </li>
            </ul>
        </div>
        
    </div>
</section>
<section id="location maps" class="container">
{% include "pages/partials/maps.html" %}
</section>
{% endblock %}

templates/pages/footer.html
    <footer class=" text-white my-primary">
      <section class="d-flex justify-content-center p-3 border-bottom"></section>

      <section class="d-flex justify-content-center">
        <div class="container text-md-start mt-5">
          <div class="row">
            <div class="col-md-3  mx-auto mb-4">
              <h5 class="text-uppercase fw-bold mb-4">
                The Guardian Agency
              </h5>
              <p>
                Learn how we can help guard your assests and provide the best
                coverage for whatever your insurance needs are.
              </p>
            </div>

            <div class="col-md-2  mx-auto mb-4">
              <h6 class="text-uppercase fw-bold mb-4">Services & Links</h6>
              <p>
                <a class="text-white" href="{% url 'home'%}">Home</a>
              </p>
              <p>
                <a class="text-white" href="{% url 'personal'%}">Personal</a>
              </p>
              <p>
                <a class="text-white" href="{% url 'commercial'%}">Commercial</a>
              </p>
              <p>
                <a class="text-white" href="{% url 'contact'%}">Contact</a>
              </p>
              <p>
                <a class="text-white" href="{% url 'about'%}">About</a>
              </p>
            </div>

            <div class="col-md-3  mx-auto mb-4">
              <h6 class="text-uppercase fw-bold mb-4">Business Hours</h6>
              <p>
                Monday - Friday
                <br />
                9:00 AM - 5:00 PM
              </p>
              <p>Saturdays by appointment</p>
            </div>

            <div class="col-md-4 mx-auto mb-md-0 mb-4">
              <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
              <p>
                33 W Higgins Rd, Suite 2100
                <br />
                South Barrington, IL 60010
              </p>
              <p>
              </p>
              <p>
                <i class="fa fa-envelope"></i>
                Personal: service@emrz-ins.com <br />
                <i class="fa fa-envelope"></i>
                Commercial: erzinsurance@gmail.com
              </p>
              <p>
                <i class="fa fa-phone"></i>
                (847) 485-1550
              </p>
              <p>
                <i class="fa fa-fax"></i>
                (847) 489-6700
              </p>
            </div>
          </div>
        </div>
      </section>
    </footer>

templates/pages/home.html
{% extends 'base.html' %}
{% load static %}
<link rel="stylesheet" type='text/css' href="{% static 'pages/pages.css' %}">
{% block content %}

{% include 'pages/partials/header.html' %}

<div id="content" class="container justify-content-center">
    {% include 'pages/partials/card.html' with title=card_title1 text=card_text1 img_src=img_src1 img_alt=img_alt1 button_link=button_link1%}
    {% include 'pages/partials/card.html' with title=card_title2 text=card_text2 img_src=img_src2 img_alt=img_alt2 button_link=button_link2%}
    {% include 'pages/partials/card.html' with title=card_title3 text=card_text3 img_src=img_src3 img_alt=img_alt3 button_link=button_link3%}
</div>

{% endblock %}

templates/pages/navbar.html
{% load static %}
<link rel="stylesheet" type='text/css' href="{% static 'pages/pages.css' %}">
<link rel="stylesheet" type='text/css' href="{% static 'pages/navbar.css' %}">
<nav class="my-primary navbar navbar-expand-lg navbar-dark sticky-top">
    <div class="container text-white">
        <a class="navbar-brand" href="{% url 'home'%}">
            <img src={% static 'images/logo.png' %} alt="The Guardian Agency logo" style="width:12rem">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
            <li class="nav-item">
                <h5><a class="nav-link text-white" href="{% url 'home'%}">Home </a></h5>
            </li>
            <li class="nav-item">
                <h5><a class="nav-link text-white" href="{% url 'personal' %}">Personal</a></h5>
            </li>
            <li class="nav-item">
                <h5><a class="nav-link text-white" href="{% url 'commercial' %}">Commercial</a></h5>
            </li>
            <li class="nav-item">
                <h5><a class="nav-link text-white" href="{% url 'contact' %}">Contact</a></h5>
            </li>
            <li class="nav-item">
                <h5><a class="nav-link text-white" href="{% url 'about' %}">About</a></h5>
            </li>
            <li class="nav-item">
                <h5><a class="nav-link text-white" href="{% url 'articles:blog' %}">Blog</a></h5>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <h5><a class="nav-link text-white" href="{% url 'staff:logout' %}">Logout</a></h5>
            </li>
            {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/pages/personal.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% include 'pages/partials/small-header.html'%}
{% include 'pages/partials/small-cards-and-features.html' %}

{% endblock %}