articles/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import ArticleCreateView, ArticleListView, ArticleUpdateView, ArticleDetailView, ArticleDeleteView

app_name = 'articles'
urlpatterns = [
    path('', ArticleListView.as_view(), name='blog'),
    path('create/', login_required(ArticleCreateView.as_view()), name='create'),
    path('<slug:slug>', ArticleDetailView.as_view(), name='detail'),
    path('<slug:slug>/update/', login_required(ArticleUpdateView.as_view()), name='update'),
    path('<slug:slug>/delete/', login_required(ArticleDeleteView.as_view()), name='delete'),
]

guardian_insurance_agency/urls.py
from django.contrib import admin
from django.urls import path, include

from pages.views import (
    HomeView,
    PersonalView,
    CommercialView,
    ContactView,
    AboutView
)

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('personal/', PersonalView.as_view(), name='personal'),
    path('commercial/', CommercialView.as_view(), name='commercial'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('about/', AboutView.as_view(), name='about'),
    path('blog/', include('articles.urls')),
    path('staff/', include('staff.urls')),
    path('admin/', admin.site.urls),
]

staff/urls.py
from django.urls import path

from .views import staff_home_view, login_view, logout_view

app_name = 'staff'
urlpatterns = [
    path('', staff_home_view, name='staff'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

articles/models.py
from django.conf import settings
from django.db import models
from django.db.models import Q, lookups
from django.db.models.signals import pre_save, post_save
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User


from .utils import slugify_instance_title

#User = settings.AUTH_USER_MODEL

# Create your models here.
class ArticleQuerySet(models.QuerySet):
    def search(self, query=None):
        if query is None or query == "":
            return self.none() # return Article.objects.none() # [] empty list
        lookups = Q(title__icontains=query) | Q(content__icontains=query)
        return self.filter(lookups) # self.get_queryset() makes this reuseable with other models


class ArticleManager(models.Manager):
    def get_queryset(self):
        return ArticleQuerySet(self.model, using=self._db)

    def search(self, query=None):
        return self.get_queryset().search(query=query)
        

class Article(models.Model):
    '''
    Article
    '''
    user = models.ForeignKey(User, blank=False, null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True, blank=True, null=True)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects=ArticleManager()

    def get_absolute_url(self):
        return reverse("articles:detail", kwargs={"slug": self.slug})

    def get_edit_url(self):
        return reverse("articles:update", kwargs={"slug": self.slug})

    def get_delete_url(self):
        return reverse("articles:delete", kwargs={"slug": self.slug})

    def get_content_preview(self):
        content_preview = f"{self.content[:375]}..."
        return content_preview
    
    # def save(self, request, *args, **kwargs):
    #     self.user = request.user
    #     super().save(*args, **kwargs)
    #     # we could do additional actions

def article_pre_save(sender, instance, *args, **kwargs): # instance is the particular instance of the model (Article) that is currently being sent
    # print('pre_save')
    if instance.slug is None:
        slugify_instance_title(instance, save=False)

pre_save.connect(article_pre_save, sender=Article)

def article_post_save(sender, instance, created, *args, **kwargs):
    # print('post_save')
    if created:
        slugify_instance_title(instance, save=True)

post_save.connect(article_post_save, sender=Article)

articles/forms.py
from django import forms

from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            new_data = {
                "placeholder": f"{str(field).capitalize()}",
                "class": "form-control"
            }
            self.fields[str(field)].widget.attrs.update(new_data)
        content_extra_data = {
            "rows": 30,
            "class": "form-control md-textarea"
        }
        self.fields['content'].widget.attrs.update(content_extra_data)

articles/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.urls.base import reverse, reverse_lazy
from django.views.generic import (
    CreateView,
    DetailView,
    UpdateView,
    ListView,
    DeleteView
)

from .models import Article
from .forms import ArticleForm

class ArticleListView(ListView):
    template_name = 'articles/list.html'
    queryset = Article.objects.all()


class ArticleDetailView(DetailView):
    template_name = 'articles/detail.html'

    def get_object(self):
        slug_ = self.kwargs.get("slug")
        return get_object_or_404(Article, slug = slug_)


class ArticleCreateView(CreateView):
    template_name = 'articles/create-update.html'
    form_class = ArticleForm
    #queryset = Article.objects.all()
    #success_url = reverse_lazy('articles:detail', kwargs={'slug': self.})
    def get_success_url(self):
        return reverse('articles:detail', kwargs={'slug':self.object.slug})

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        print(self.request.user)
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class ArticleUpdateView(UpdateView):
    template_name = 'articles/create-update.html'
    form_class = ArticleForm
    queryset = Article.objects.all()

    def get_object(self):
        slug_ = self.kwargs.get("slug")
        return get_object_or_404(Article, slug=slug_)

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)


class ArticleDeleteView(DeleteView):
    template_name = 'articles/delete.html'

    def get_object(self):
        slug_ = self.kwargs.get("slug")
        return get_object_or_404(Article, slug=slug_)

    def get_success_url(self):
        return reverse('articles:blog')

articles/templates/articles/create-update.html
{% extends 'base.html' %} 
{% block content %} 


<div class="container mt-3">
    <form action="." method="POST"> {% csrf_token %}
        {% comment %} {{ form.as_p }} {% endcomment %}
        <div class="md-form mb-2">
            {{ form.title.errors }}
            <label for="{{form.title.id_for_lable }}">Article Title</label>
            {{ form.title }}
        </div>
        <div class="md-form mb-2">
            {{ form.content.errors }}
            <label for="{{ form.content.id_for_lable }}">Article Content</label>
            {{ form.content }}
        </div>
        <input class="btn btn-primary my-2" type="submit" value='Submit'>
    </form>
</div>


{% endblock content %}

articles/templates/articles/delete.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <form method="POST"> {% csrf_token %}
        <h1 class="text-center">Do you want to delete the article "{{ object.title }}?"</h1>
        <p class="text-center"><input class="btn btn-secondary"type="submit" value="Yes"> <a href="{% url 'articles:blog' %}">Cancel</a></p>
    </form>
</div>

{% endblock %}

articles/templates/articles/detail.html
{% extends 'base.html' %} {% block content %}
{% load static %}
<div class="container">
    <div class="mt-2">
    <h1> {{ object.title }} </h1> 
    <h3>Author: {{ object.user.first_name }} {{ object.user.last_name }}</h3>
    </div>
    <div class="row">
        <div class="col-md-9">
            {% if request.user.is_authenticated %}
                <a class="btn btn-primary" href="{{ object.get_edit_url }}">Edit</a>
                <a class="btn btn-secondary" href="{{ object.get_delete_url }}">Delete</a>
            {% endif %}
            <div class="lead mt-2">
                <p class="">{{ object.content|linebreaks }}</p>
            </div>
        </div>
        <div class="col-md-3">
            {% include 'articles/partials/sidebar.html' %}
        </div> 
    </div>
</div>
{% endblock content %}

articles/templates/articles/list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" type='text/css' href="{% static 'articles/list.css' %}">

<div class="jumbotron rounded-0 text-white justify-content-center align-items-center" style="background-image: linear-gradient(to bottom, rgba(0,0,0,0.6) 0%,rgba(0,0,0,0.6) 100%), url({%static 'images/blog.png' %})">
  <h1 class="text-center text-responsive-large">Blog</h1>
  <h5 class="text-center text-responsive-smaller">Learn more about what makes a good insurance policy by reading our blogs</h5>
  </p>
</div>

<div class="container">
{% if request.user.is_authenticated %}
{% comment %} <h5><a href="{% url 'articles:create' %}">Create New Article</a></h5> {% endcomment %}
<a href="{% url 'articles:create' %}"type="button" class="btn btn-primary btn-lg text-white">Create New Article</a>
{% endif %}

{% for instance in object_list %}
    <a class="text-reset text-decoration-none" href="{{ instance.get_absolute_url }}">
        <div class="card my-3">
            <h2 class="card-header">{{ instance.title }}</h2>
            <div class="card-body">
                <h5 class="card-title">{{ instance.created_at.date }}</h5>
                <p class="card-text lead">{{ instance.get_content_preview }}</p>
                <a href="{{ instance.get_absolute_url }}" class="btn btn-primary mt-2">Read Article</a>
            </div>
        </div>
    </a>
{% endfor %}

</div>
{% endblock %}