guardian_insurance_agency/urls.py
from django.contrib import admin
from django.urls import path, include

from pages.views import (
    HomeView,
    PersonalView,
    CommercialView,
    ContactView,
    AboutView
)

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('personal/', PersonalView.as_view(), name='personal'),
    path('commercial/', CommercialView.as_view(), name='commercial'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('about/', AboutView.as_view(), name='about'),
    path('blog/', include('articles.urls')),
    path('staff/', include('staff.urls')),
    path('admin/', admin.site.urls),
]

staff/urls.py
from django.urls import path

from .views import staff_home_view, login_view, logout_view

app_name = 'staff'
urlpatterns = [
    path('', staff_home_view, name='staff'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

staff/models.py
from django.db import models

# Create your models here.

staff/views.py
from django.conf.urls import url
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect
from django.urls.base import reverse, reverse_lazy

# Create your views here.
def staff_home_view(request):
    return render(request, "staff/home.html")

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('/')
    else:
        form = AuthenticationForm(request)
    context = {
        "form": form
    }
    return render(request, "staff/login.html", context=context)

def logout_view(request):
    if request.method == "POST":
        logout(request)
        #return redirect(url('', staff_home_view))
        return redirect('/staff')
    return render(request, "staff/logout.html", {})

staff/templates/staff/home.html
{% extends 'base.html' %}

{% block content %}

<div class="container text-center mt-5">
    {% if not request.user.is_authenticated %}
    <p>Would you like to login? <a href="{% url 'staff:login' %}">Login</a></p>
    {% else %}
    <p>You're already logged in. Would you like to <a href="{%url 'staff:logout' %}">Logout</a>?</p>
    {% endif %}
</div>

{% endblock %}

staff/templates/staff/login.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    {% if not request.user.is_authenticated %}
    <div style="margin-top:30px">
        <form method="POST"action=""> {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-primary" type='submit'>Login</button>
        </form>
    </div>
    {% else %}
    <p>You're already logged in. Would you like to <a href="/logout/">logout</a>?</p>
    {% endif %}
</div>

{% endblock %}

staff/templates/staff/logout.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    {% if request.user.is_authenticated %}
    <div style="margin-top:30px">
        <form method="POST"action=""> {% csrf_token %}
            <p>Are you sure you want to logout?</p>
            <button type='submit'>Yes, logout.</button>
        </form>
    </div>
    {% else %}
    <p>You're not logged in. Would you like to <a href="{% url 'staff:login' %}">login</a>?</p>
    {% endif %}
</div>

{% endblock %}